# Database
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/portfolio
spring.datasource.username=portfolio_user
spring.datasource.password=portfolio_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# App
server.port=9090
spring.application.name=portfolio

# Email
spring.config.import=optional:application-secrets.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=priyanshumisra3141@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2