# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/portfolio}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:portfolio_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:portfolio_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# App
server.port=9090
spring.application.name=portfolio

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=priyanshumisra3141@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2